no message

diff --git a/.github/workflows/link-ticket.yml b/.github/workflows/link-ticket.yml
--- a/.github/workflows/link-ticket.yml
+++ b/.github/workflows/link-ticket.yml
@@ -2,73 +2,81 @@ name: Attach PR to Trello Ticket
 
 on:
   pull_request:
-    types: [opened]
+    types: [opened, synchronize]
     branches:
       - development
 
 jobs:
-  link-ticket:
+  capture-ticket-id:
     runs-on: ubuntu-latest
-    steps:    
-    - name: Safe Handling of PR Body
-      run: |
-        ENCODED_BODY=$(echo "${{ github.event.pull_request.body }}" | base64 -w 0)
-        echo "ENCODED_BODY=$ENCODED_BODY" >> $GITHUB_ENV
+    outputs:
+      card_id: ${{ steps.extract-card-id.outputs.card_id }}
+      skip: ${{ steps.check-comment.outputs.skip }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-    - name: Extract Trello Card ID from Encoded Branch Name or PR Body
-      run: |
-        PR_BODY=$(echo "$ENCODED_BODY" | base64 --decode)
-        BRANCH_NAME="${{ github.head_ref }}"
-        TRELLO_CARD_ID=$(echo "$BRANCH_NAME" | grep -oP '(?i:task)_\K[A-Za-z0-9]+' || echo "")
+      - name: Check for existing Trello link comment
+        id: check-comment
+        run: |
+          COMMENTS_URL=${{ github.event.pull_request.comments_url }}
+          COMMENT_FOUND=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $COMMENTS_URL | jq -r '.[] | select(.body | test("^Linked Ticket:")) | select(.user.login == "tifapp") | .body')
+          if [[ -n "$COMMENT_FOUND" ]]; then
+            echo "Found Linked Ticket Comment. Skipping job."
+            echo "::set-output name=skip::true"
+          else
+            echo "::set-output name=skip::false"
+          fi          
 
-        if [[ -z "$TRELLO_CARD_ID" ]]; then
-          TRELLO_CARD_ID=$(echo "$PR_BODY" | grep -oP '(?i:task)_\K[A-Za-z0-9]+' || echo "")
-        fi
+      - name: Safe Handling of PR Body
+        run: |
+          ENCODED_BODY=$(echo "${{ github.event.pull_request.body }}" | base64 -w 0)
+          echo "ENCODED_BODY=$ENCODED_BODY" >> $GITHUB_ENV
 
-        if [[ -z "$TRELLO_CARD_ID" ]]; then
-          echo "No card ID found in branch name or PR body."
-          exit 1
-        else
-          echo "Found Card ID: $TRELLO_CARD_ID"
-          echo "::set-output name=card_id::$TRELLO_CARD_ID"
-        fi
+      - name: Extract Trello Card ID from Branch Name or PR Body
+        id: extract-card-id
+        run: |
+          BRANCH_NAME="${{ github.head_ref }}"
+          PR_BODY=$(echo "$ENCODED_BODY" | base64 --decode)
+          # Using regex to extract card ID that starts with 'task_' followed by alphanumeric characters
+          TRELLO_CARD_ID=$(echo "$BRANCH_NAME" | grep -oP '(?i:task)_\K[A-Za-z0-9]+' || echo "$PR_BODY" | grep -oP '(?i:task)_\K[A-Za-z0-9]+' || echo "")
+          if [[ -z "$TRELLO_CARD_ID" ]]; then
+            echo "No card ID found in branch name or PR body."
+          else
+            echo "Found Card ID: $TRELLO_CARD_ID"
+            echo "::set-output name=card_id::$TRELLO_CARD_ID"
+          fi
 
-    - name: Link PR and Trello Ticket
-      env:
-        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
-        TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
-        USER_GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
-      run: |
-        TRELLO_CARD_ID="${{ steps.card_id.outputs.card_id }}"
+  link-ticket:
+    needs: capture-ticket-id
+    if: ${{ !needs.capture-ticket-id.outputs.skip }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Link PR and Trello Ticket
+        run: |
+          TRELLO_CARD_ID="${{ needs.capture-ticket-id.outputs.card_id }}"
+          TRELLO_CARD_URL="https://trello.com/c/$TRELLO_CARD_ID"
+          PR_URL="${{ github.event.pull_request.html_url }}"
+          PR_NAME="Pull Request #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
 
-        # Define Card URL
-        TRELLO_CARD_URL="https://trello.com/c/$TRELLO_CARD_ID"
-
-        # URL of the Pull Request
-        PR_URL="${{ github.event.pull_request.html_url }}"
-        PR_NAME="Pull Request #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
-
-        # Attach PR to Trello Card
-        TRELLO_RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST "https://api.trello.com/1/cards/$TRELLO_CARD_ID/attachments" \
-        -d "key=${TRELLO_API_KEY}" \
-        -d "token=${TRELLO_API_TOKEN}" \
-        -d "url=${PR_URL}" \
-        -d "name=${PR_NAME}")
-        echo "Trello API Response Code: $TRELLO_RESPONSE"
-        echo "Trello API Response Body:"
-        cat response.json
-
-        if [[ "$TRELLO_RESPONSE" -ne 200 ]]; then
-          echo "Failed to attach PR to card. Response code: $TRELLO_RESPONSE"
+          TRELLO_RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST "https://api.trello.com/1/cards/$TRELLO_CARD_ID/attachments" \
+          -d "key=${{ secrets.TRELLO_API_KEY }}" \
+          -d "token=${{ secrets.TRELLO_API_TOKEN }}" \
+          -d "url=$PR_URL" \
+          -d "name=$PR_NAME")
+          echo "Trello API Response Code: $TRELLO_RESPONSE"
           cat response.json
-          exit 1
-        else
-          echo "PR successfully attached to Trello card."
-        fi
-        
-        # Comment on the GitHub PR with the card link
-        COMMENT_BODY="Linked Ticket: $TRELLO_CARD_URL"
-        curl -s -H "Authorization: token $USER_GITHUB_TOKEN" \
-        -H "Accept: application/vnd.github.v3+json" \
-        -d "{\"body\": \"$COMMENT_BODY\"}" \
-        "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
+
+          if [[ "$TRELLO_RESPONSE" -ne 200 ]]; then
+            echo "Failed to attach PR to card. Response code: $TRELLO_RESPONSE"
+            cat response.json
+            exit 1
+          else
+            echo "PR successfully attached to Trello card."
+          fi
+            
+          COMMENT_BODY="Linked Ticket: $TRELLO_CARD_URL"
+          curl -s -H "Authorization: token ${{ secrets.USER_GITHUB_TOKEN }}" \
+          -H "Accept: application/vnd.github.v3+json" \
+          -d "{\"body\": \"$COMMENT_BODY\"}" \
+          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
